# Generated by Django 2.2 on 2019-04-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(blank=True, max_length=50, null=True)),
                ('telefone', models.IntegerField(null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
